services:
  - type: web
    name: sdental-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT run:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sdental-db
          property: connectionString
      - key: CLAUDE_API_KEY
        sync: false
      - key: EVOLUTION_API_URL
        sync: false
      - key: EVOLUTION_API_KEY
        sync: false

databases:
  - name: sdental-db
    plan: free
    databaseName: sdental
    user: sdental
